spring:
  datasource:
    url: jdbc:h2:mem:trexis_dev_team
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console.enabled: true